[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "ffmpeg>=1.4",
    "plyer>=2.1.0",
    "requests>=2.32.5",
    "yt-dlp>=2025.10.22",
]
